SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Hernan Velo
-- Developer:	Andres Gonzalez
-- Description:	Visualizador de pagos
-- =============================================
CREATE PROCEDURE viewPayments
		(@ABHDueDate	datetime)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

SELECT [VoucherID]
      ,[CompanyCode]
      ,[VoucherType]
      ,[CreationDateTime]
      ,[CreationUser]
      ,[VoucherAmount]
      ,[PaidAmount]
      ,[VoucherBalance]
      ,[OpenStatusFlag]
      ,[CompanyInvoiceNumber]
      ,[CompanyInvoiceDate]
      ,[CompanyInvoiceDueDate]
      ,[CompanyTerms]
      ,[AdjustedAmount]
      ,[LoadNum]
      ,[LoadBookID]
      ,[DebitAccount]
      ,[CreditAccount]
      ,[Notes]
      ,[LastPaidDate]
      ,[LastCheckNumber]
      ,[DiscountPercent]
      ,[DiscountAmount]
      ,[ABHDueDate]
      ,[ApprovalUser]
      ,[ApprovalDateTime]
      ,[ReleasedDate]
      ,[VoucherBatchID]
      ,[LoadBillTo]
      ,[Batchnotes]
      ,[ReleasedBy]
      ,[FirstInvoicePrintDate]
      ,[RateApproved]
      ,[ownedbyabh]
      ,[BranchCode]
      ,[GLCompanyCode]
      ,[SourceMode]
      ,[PaymentStyle]
      ,[SalesRep]
      ,[ActivityDate]
      ,[CHRApplication]
      ,[OrderNum]
      ,[PAOID]
      ,[QuickPayFlag]
      ,[Role]
      ,[RoleSeqNum]
      ,[ExchangeRate]
      ,[SourceCurrencyCode]
      ,[SourceVoucherAmount]
      ,[SourceVoucherBalance]
      ,[PFLFlag]
      ,[SourcePaidAmount]
      ,[SourceAdjustedAmount]
      ,[FunctionalCurrency]
      ,[RollupID]
      ,[AssetID]
      ,[VoucherHeaderID]
      ,[VATRateCode]
      ,[PayStatus]
      ,[FinancialStatusID]
      ,[FinancialItemID]
      ,[VoucherDocID]
      ,[CommissionItemID]
      ,[ExchangeSetID]
      ,[EftDFI]
      ,[EftDFIType]
      ,[EftBankAccount]
      ,[EftBankAccountType]
      ,[DBNum]
      ,[RailEft]
      ,[NormalPaymentMethod]
      ,[QuickPaymentMethod]
      ,[RemittanceMethod]
      ,[FaxRemittanceTo]
      ,[EmailRemittanceTo]
      ,[NameOnAccount]
      ,[BankName]
      ,[BankPhone]
      ,[QuickPay]
      ,[DiscAllowed]
      ,[DiscPercent]
      ,[TChekAcctNum]
      ,[PinChangedDate]
      ,[PinMailedFlag]
      ,[LastUpdateUser]
      ,[LastUpdateDate]
      ,[Pin]
      ,[AttnFaxTo]
      ,[TChekCurrencies]
      ,[WireNotes]
      ,[WireRoutingNumber]
      ,[WireAcctNum]
      ,[WireCurrency]
      ,[WireBankName]
      ,[WireCity]
      ,[WireCountry]
      ,[NoTChek]
      ,[ClaimAmount]
      ,[BillStatus]
      ,[DaysToPay]
      ,[ClaimAmountCurrency]
      ,[FactoringID]
      ,[EFTBankCountry]
      ,[IBANCountry]
      ,[IBANKey]
      ,[TraiteDaysToPay]
      ,[QuickPayPercent]
      ,[BillStatusNotes]
      ,[TChekAcctNumCAD]
      ,[CurrencyCode]
      ,[AllowIVRSettlement]
      ,[IVRSettlementCode]
      ,[KeepNegsInBranch]
      ,[PartyName]
  FROM [dbo].[viewPaymentsMxMock]
	WHERE ABHDueDate = @ABHDueDate ORDER BY CompanyCode ASC

END
GO


GO


